name: DocSearch Scraper

on:
  workflow_dispatch:

env:
  ALGOLIA_APP_ID: ${{vars.ALGOLIA_APP_ID}}
  TYPESENSE_NODE: ${{vars.TYPESENSE_NODE}}
  TYPESENSE_SEARCH_ONLY_API_KEY: ${{secrets.TYPESENSE_SEARCH_ONLY_API_KEY}}

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run DocSearch Scraper
        uses: celsiusnarhwal/typesense-scraper@v2
        with:
          # The secret containing your Typesense API key. Required.
          api-key: ${{ secrets.TYPESENSE_ADMIN_API_KEY }}
          
          # The hostname or IP address of your Typesense server. Required.
          host: ${{vars.TYPESENSE_NODE}}
          
          # The port on which your Typesense server is listening. Optional. Default: 8108.
          port: 8108
          
          # The protocol to use when connecting to your Typesense server. Optional. Default: http.
          protocol: http
          
          # The path to your DocSearch config file. Optional. Default: docsearch.config.json.
          config: docsearch.config.json
